
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateCertificate = (transformer: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    doc.setFontSize(18);
    doc.text("Transformer Test Certificate", pageWidth / 2, 15, { align: 'center' });

    doc.setFontSize(10);
    doc.text(`Certificate Generated: ${new Date().toLocaleDateString()}`, pageWidth - 15, 15, { align: 'right' });

    // --- Transformer Details ---
    doc.setFontSize(12);
    doc.text("Transformer Details", 14, 30);

    autoTable(doc, {
        startY: 35,
        head: [['Job ID', 'Unique ID', 'Rating', 'Voltage Class', 'Trafo Name']],
        body: [[
            transformer.jobId || '-',
            transformer.uniqueId || '-',
            transformer.rating || '-',
            transformer.voltageClass || '-',
            transformer.name || '-'
        ]],
        theme: 'striped',
        headStyles: { fillColor: [41, 128, 185] }
    });

    let currentY = (doc as any).lastAutoTable.finalY + 15;

    // --- Reports Loop ---
    const results = transformer.testHistory?.secondary_test || {};

    // Helper to print section header
    const printSectionHeader = (title: string) => {
        if (currentY > 250) {
            doc.addPage();
            currentY = 20;
        }
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black
        doc.text(title, 14, currentY);
        currentY += 5;
    };

    // 1. Metering Results
    if (results.metering_results && results.metering_results.length > 0) {
        printSectionHeader("Metering Core Results");

        results.metering_results.forEach((res: any, idx: number) => {
            doc.setFontSize(10);
            doc.text(`Ratio: ${res.ratioValue || `Config ${idx + 1}`} (ID: ${res.internalCoreNo || res.coreId || '-'})`, 14, currentY + 5);

            const rows = res.rows ? res.rows.map((r: any) => [
                r.current, r.r100, r.p100, r.r25, r.p25
            ]) : [];

            autoTable(doc, {
                startY: currentY + 7,
                head: [['Current', 'R-100%', 'P-100%', 'R-25%', 'P-25%']],
                body: rows,
                theme: 'grid',
                headStyles: { fillColor: [52, 152, 219] },
                styles: { fontSize: 8 },
                margin: { left: 14 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 10;
        });
    }

    // 2. Protection Results
    if (results.protection_results && results.protection_results.length > 0) {
        printSectionHeader("Protection Core Results");

        // Prepare table body directly as rows are flat objects in array
        const body = results.protection_results.map((res: any) => [
            res.ratioValue || '-',
            res.internalCoreNo || res.coreId || '-',
            res.burden100_1 || '-',
            res.burden100_2 || '-',
            res.resistance || '-',
            res.secondaryLimitingVtg || '-',
            res.excitationCurrent || '-',
            res.compositeError || '-'
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['Ratio', 'Core ID', 'B-100(1)', 'B-100(2)', 'Res', 'V-Lim', 'I-Exc', 'Comp Err']],
            body: body,
            theme: 'grid',
            headStyles: { fillColor: [46, 204, 113] },
            styles: { fontSize: 8 }
        });
        currentY = (doc as any).lastAutoTable.finalY + 15;
    }

    // 3. PS Results
    if (results.ps_results && results.ps_results.length > 0) {
        printSectionHeader("PS Core Results");

        const body = results.ps_results.map((res: any) => [
            res.ratioValue || '-',
            res.internalCoreNo || res.coreId || '-',
            res.turnRatioError || '-',
            res.resistance || '-',
            res.vk || '-',
            res.vkVal || '-',
            res.iexVk || '-',
            res.iex11Vk || '-'
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['Ratio', 'Core ID', 'Ratio Err', 'Res', 'Vk', 'Vk Val', 'Iex(Vk)', 'Iex(1.1Vk)']],
            body: body,
            theme: 'grid',
            headStyles: { fillColor: [155, 89, 182] },
            styles: { fontSize: 8 }
        });
        currentY = (doc as any).lastAutoTable.finalY + 15;
    }

    // --- Footer ---
    doc.setFontSize(8);
    doc.text("Generated by Advent Engineers Testing Panel", 14, 290);

    // Save
    doc.save(`Certificate_${transformer.uniqueId}.pdf`);
};
